import { ArrowLeft, ArrowUpRight } from "lucide-react";
import Image from "next/image";
import type { Metadata } from "next";
import { notFound } from "next/navigation";

type Section = { eyebrow: string; title: string; intro: string; body: string; links: Array<[string, string]> };

const sections: Record<string, Section> = {
  about: { eyebrow: "About APIN", title: "People, expertise and history for stronger public health.", intro: "Discover APIN's story, mission, technical capabilities and leadership in one place.", body: "", links: [["Where we work", "/where-we-work"], ["HIV/AIDS programme", "/hiv-aids"]] },
  timeline: { eyebrow: "Our story", title: "A Nigerian institution built for public health.", intro: "APIN Public Health Initiatives focuses on prevention, care and treatment for HIV/AIDS, TB and malaria, alongside technical assistance to government.", body: "2000 - The Harvard School of Public Health initiated HIV/AIDS research and prevention in Nigeria, funded by the Bill & Melinda Gates Foundation.\n\n2004 - Implementation began with HIV/AIDS prevention, care and treatment through PEPFAR funding.\n\n2007 - APIN became an independent NGO to build local capacity and sustainability.\n\n2008 - APIN received its first grant as an independent grantee.\n\n2018 - The organisation rebranded from AIDS Prevention Initiative in Nigeria to APIN Public Health Initiatives.\n\nPresent day - APIN is a direct implementing partner to the U.S. CDC and works with the Federal Government of Nigeria on policy, service delivery, infrastructure and workforce capacity.", links: [["Mission, vision & values", "/mission-vision-values"], ["Our expertise", "/expertise"], ["Our team", "/our-team"]] },
  "mission-vision-values": { eyebrow: "Mission, vision & values", title: "Equity-oriented health interventions that last.", intro: "People, technology and other resources come together to deliver high-quality and innovative health interventions.", body: "Mission\nTo leverage people, technology, and other resources to deliver high-quality, innovative, and equity-oriented health interventions.\n\nVision\nTo be a leading development organization committed to improving health in Nigeria and beyond.\n\nAPIN's work is guided by a culture of service, partnership, innovation and excellence.", links: [["Our story", "/timeline"], ["Our expertise", "/expertise"], ["Meet our team", "/our-team"]] },
  expertise: { eyebrow: "Our expertise", title: "Technical depth, local knowledge and practical delivery.", intro: "Eight capability areas support APIN's work across public health programmes and institutions.", body: "1. Community Directed Interventions - Social support systems for HIV/AIDS, SRH and MNCH programmes using community organisations and all three tiers of government.\n\n2. Clinical Laboratory Infrastructure - Quality laboratory and diagnostic infrastructure, point-of-care devices and equipment procurement.\n\n3. Health Management Information Systems - More than 10 years deploying EMR systems and clinical decision support tools at 500+ HIV clinics in 8 states.\n\n4. Training and Capacity Building - Certified CPD provider with experience training doctors and developing clinical training resources.\n\n5. Implementing and Technical Assistance - Service delivery assessment, patient flow redesign, SOP development, testing, linkage, advocacy, care and treatment.\n\n6. Logistics and Supply Chain - More than 16 years of commodity logistics, warehousing and redistribution.\n\n7. Organisation Development - Capacity building for hospitals and 40+ civil society organisations.\n\n8. Research, Monitoring and Evaluation - More than 80 peer-reviewed articles and 100 conference abstracts in the last five years.", links: [["HIV/AIDS programme", "/hiv-aids"], ["Where we work", "/where-we-work"], ["Success stories", "/success-stories"]] },
  "our-team": { eyebrow: "Our team", title: "People who make public health systems stronger.", intro: "APIN's management and technical teams bring expertise across epidemiology, clinical care, laboratories, finance, procurement and community services.", body: "Management team\nProf. Prosper Okonkwo - pioneer CEO since 2007; Professor of Infectious Disease Epidemiology at Bingham University.\n\nMr. Niyi Olaofin - Deputy CEO, Shared Services.\n\nDr Jay Osi Samuels - Deputy CEO, Programs.\n\nPharm. Oluremi (Remi) Olaitan - Director, Special Services.\n\nDr Ifeyinwa (Ify) Onwuatuelo - Coordinating Director.\n\nDr. Olabanjo Okunlola Ogunsola - Director, Non-Communicable Diseases and New Business Development.\n\nOther directors and associate directors lead laboratory and health systems strengthening, strategic information, HR, finance, grants, prevention, care, procurement, community services, IT and internal audit.", links: [["Our story", "/timeline"], ["Board and governance", "/accountability"], ["Careers", "/careers"]] },
  "where-we-work": { eyebrow: "Where we work", title: "Local knowledge. National reach.", intro: "APIN works across all 36 states and the Federal Capital Territory of Nigeria.", body: "Abia, Adamawa, Akwa Ibom, Anambra, Bauchi, Bayelsa, Benue, Borno, Cross River, Delta, Ebonyi, Edo, Ekiti, Enugu, Gombe, Imo, Jigawa, Kaduna, Kano, Katsina, Kebbi, Kogi, Kwara, Lagos, Nasarawa, Niger, Ogun, Ondo, Osun, Oyo, Plateau, Rivers, Sokoto, Taraba, Yobe, Zamfara and Abuja.", links: [["Our expertise", "/expertise"], ["HIV/AIDS programme", "/hiv-aids"], ["Success stories", "/success-stories"]] },
  "success-stories": { eyebrow: "Success stories", title: "Evidence from the work and the people behind it.", intro: "Stories from APIN programmes across governance, nutrition, prevention and community support.", body: "Strengthening National Governance and Oversight of Infection Prevention and Control Implementation Across CDC-Supported Sites\n\nBefore Meets After: Addressing Malnutrition through the OVC Programme\n\nEmbracing New Approaches to Preventing New HIV Infections - Community and Congregational Approach to PMTCT\n\nAPIN's and MIED's Dynamic Approach to Ending Food Insecurity and Malnutrition in Benue State\n\nBenue: Helping Women Thrive\n\nOyo: From HIV Positive to Mentor Mother", links: [["Our impact", "/impact"], ["HIV/AIDS programme", "/hiv-aids"], ["Knowledge centre", "/knowledge"]] },
  "hiv-aids": { eyebrow: "HIV/AIDS programme", title: "Contributing to Nigeria's national HIV response.", intro: "For more than 17 years, APIN has strengthened HIV prevention, care, treatment and community support.", body: "APIN implemented GH1058 from 2008 to 2013 and CARES from 2013 to 2017. The programme has supported approximately 250,000 people living with HIV, placed more than 150,000 people on ART at 70+ clinics in 10+ states, and delivered full service packages to 147,714 orphans and vulnerable children.\n\nOther reported cumulative results include 391,955 people reached with prevention messages, 4,145,664 people counselled and tested, approximately 1,000,000 pregnant women counselled and tested, and nearly 50,000 HIV-positive pregnant women given PMTCT drugs. APIN has operated in more than 500 health centres and clinics.", links: [["Our expertise", "/expertise"], ["Where we work", "/where-we-work"], ["Success stories", "/success-stories"]] },
  impact: { eyebrow: "Our impact", title: "Evidence that moves health forward.", intro: "Explore the scale, reach and outcomes of APIN's public-health programmes.", body: "APIN reports millions of HIV tests delivered, hundreds of thousands of people living with HIV supported, tuberculosis treatment outcomes and extensive health-facility support across Nigeria. This section will expand into a fully sourced impact hub with programme-level indicators, methodology and case studies.", links: [["Success stories", "/success-stories"], ["Where we work", "/where-we-work"], ["Knowledge centre", "/knowledge"]] },
  knowledge: { eyebrow: "Knowledge centre", title: "Research, publications and lessons from implementation.", intro: "A growing library of APIN research, reports, publications and practical learning.", body: "This section will become a searchable knowledge centre for peer-reviewed publications, reports, policy briefs, newsletters, case studies and other public-health resources.", links: [["Our expertise", "/expertise"], ["Success stories", "/success-stories"], ["Contact APIN", "/contact"]] },
  accountability: { eyebrow: "Accountability & governance", title: "Responsible leadership and transparent public-health delivery.", intro: "Governance, stewardship and accountability are essential to sustainable health programmes.", body: "This section will bring together APIN governance information, board leadership, policies and accountability resources in a clearer, more accessible format.", links: [["Our team", "/our-team"], ["Our story", "/timeline"], ["Contact APIN", "/contact"]] },
  careers: { eyebrow: "Careers", title: "Bring your expertise to work that improves health.", intro: "Current opportunities and application details will be published as roles become available.", body: "APIN teams work across technical disciplines, operations, research, laboratories, data, finance and community engagement. Contact APIN for current recruitment information.", links: [["Contact APIN", "/contact"], ["Our team", "/our-team"]] },
  contact: { eyebrow: "Contact", title: "Connect with APIN.", intro: "APIN Public Health Initiatives works from Abuja, Lagos and communities across Nigeria.", body: "Corporate headquarters\nPlot 1551, Apo Resettlement Zone E, FCT, Abuja\n\nPhone: 02092915437\nEmail: info@apin.org.ng", links: [["Our story", "/timeline"], ["Partner with APIN", "/contact"]] },
};

const aboutSections = [
  ["Our story", "A Nigerian institution built for public health.", "2000 - The Harvard School of Public Health initiated HIV/AIDS research and prevention in Nigeria, funded by the Bill & Melinda Gates Foundation.\n\n2004 - Implementation began with HIV/AIDS prevention, care and treatment through PEPFAR funding.\n\n2007 - APIN became an independent NGO to build local capacity and sustainability.\n\n2008 - APIN received its first grant as an independent grantee.\n\n2018 - The organisation rebranded from AIDS Prevention Initiative in Nigeria to APIN Public Health Initiatives.\n\nPresent day - APIN is a direct implementing partner to the U.S. CDC and works with the Federal Government of Nigeria on policy, service delivery, infrastructure and workforce capacity."],
  ["Mission & values", "Equity-oriented health interventions that last.", "Mission\nTo leverage people, technology, and other resources to deliver high-quality, innovative, and equity-oriented health interventions.\n\nVision\nTo be a leading development organization committed to improving health in Nigeria and beyond.\n\nAPIN's work is guided by a culture of service, partnership, innovation and excellence."],
  ["Our expertise", "Technical depth, local knowledge and practical delivery.", "Community Directed Interventions; clinical laboratory infrastructure; health management information systems; training and capacity building; implementing and technical assistance; logistics and supply chain management; organisation development; and research, monitoring and evaluation."],
  ["Our team", "People who make public health systems stronger.", "Management team\nProf. Prosper Okonkwo - pioneer CEO since 2007; Professor of Infectious Disease Epidemiology at Bingham University.\n\nMr. Niyi Olaofin - Deputy CEO, Shared Services.\n\nDr Jay Osi Samuels - Deputy CEO, Programs.\n\nPharm. Oluremi (Remi) Olaitan - Director, Special Services.\n\nDr Ifeyinwa (Ify) Onwuatuelo - Coordinating Director.\n\nDr. Olabanjo Okunlola Ogunsola - Director, Non-Communicable Diseases and New Business Development.\n\nOther directors and associate directors lead laboratory and health systems strengthening, strategic information, HR, finance, grants, prevention, care, procurement, community services, IT and internal audit."],
] as const;

export function generateStaticParams() { return Object.keys(sections).map((slug) => ({ slug })); }

export function generateMetadata({ params }: { params: { slug: string } }): Metadata {
  const section = sections[params.slug];
  return { title: section ? `${section.eyebrow} | APIN` : "APIN Public Health Initiatives" };
}

export default function SectionPage({ params }: { params: { slug: string } }) {
  const section = sections[params.slug];
  if (!section) notFound();
  if (params.slug === "about") {
    return (
      <main className="inner-page">
        <header className="inner-header"><a className="brand" href="/"><Image className="brand-logo" src="/APIN-PUBLIC-HEALTH-INITIATIVES-Logo.webp" alt="APIN Public Health Initiatives" width={210} height={210} priority /></a><a className="underlined-link" href="/">Back to home <ArrowUpRight size={15} /></a></header>
        <section className="inner-hero"><p className="eyebrow">About APIN</p><h1>People, expertise and history for stronger public health.</h1><p className="inner-intro">Discover APIN's story, mission, technical capabilities and leadership in one place.</p></section>
        {aboutSections.map(([eyebrow, title, body], index) => <section className="inner-content about-section" id={eyebrow.toLowerCase().replace(/[^a-z]+/g, "-")} key={eyebrow}><div><p className="section-kicker">0{index + 1} / {eyebrow}</p><h2>{title}</h2></div><p className="inner-body">{body}</p></section>)}
        <footer className="inner-footer"><a href="/"><ArrowLeft size={16} /> APIN Public Health Initiatives</a><span>Abuja · Lagos · Across Nigeria</span></footer>
      </main>
    );
  }
  return (
    <main className="inner-page">
      <header className="inner-header"><a className="brand" href="/"><Image className="brand-logo" src="/APIN-PUBLIC-HEALTH-INITIATIVES-Logo.webp" alt="APIN Public Health Initiatives" width={210} height={210} priority /></a><a className="underlined-link" href="/">Back to home <ArrowUpRight size={15} /></a></header>
      <section className="inner-hero"><p className="eyebrow">{section.eyebrow}</p><h1>{section.title}</h1><p className="inner-intro">{section.intro}</p></section>
      <section className="inner-content"><div><p className="section-kicker">The work</p><p className="inner-body">{section.body}</p></div><div className="inner-links">{section.links.map(([label, href]) => <a href={href} key={href}>{label}<ArrowUpRight size={17} /></a>)}</div></section>
      <footer className="inner-footer"><a href="/"><ArrowLeft size={16} /> APIN Public Health Initiatives</a><span>Abuja · Lagos · Across Nigeria</span></footer>
    </main>
  );
}